// <auto-generated />
using AlunosProvas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlunosProvas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210415053606_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlunosProvas.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bolsista")
                        .HasColumnType("bit");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            bolsista = false,
                            city = "RP",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 2,
                            bolsista = true,
                            city = "SJC",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 3,
                            bolsista = false,
                            city = "SP",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 4,
                            bolsista = false,
                            city = "SJC",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 5,
                            bolsista = true,
                            city = "Franca",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 6,
                            bolsista = false,
                            city = "SJC",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 7,
                            bolsista = false,
                            city = "SP",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 8,
                            bolsista = true,
                            city = "SP",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 9,
                            bolsista = false,
                            city = "SJC",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        },
                        new
                        {
                            Id = 10,
                            bolsista = true,
                            city = "Franca",
                            cpf = "656565656",
                            idade = 28,
                            nome = "Andre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
